spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://pre016-db.cwpdnskv7nsg.ap-northeast-2.rds.amazonaws.com:3306/stackoverflow_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    username: '${MYSQL_DATABASE_USERNAME}'
    password: '${MYSQL_DATABASE_PASSWORD}'
  jpa:          #JPA 설정
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
logging:         #로그 레벨 설정
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: '${JWT_SECRET_KEY}'
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420